name: Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      Tag:
        required: true
        type: choice
        options:
          - akto_staging1
          - akto_staging2
          - akto_staging3
        default: akto_staging1
      Environment:
        required: true
        type: choice
        options:
          - prod
          - staging
        default: staging  
      Deploy:
        description: 'Deploy to flash staging'
        required: false
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          architecture: x64

      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Prepare Dashboard UI
        working-directory: ./apps/dashboard/
        run: npm install && npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "ASIAQTQA3ZYG5G4BS7DU"
          aws-secret-access-key: "q1uWh2gPidMGJNvGpFnyuNQ6MYtIBO0ezJwwTem6"
          aws-session-token: "IQoJb3JpZ2luX2VjEG0aCXVzLWVhc3QtMSJHMEUCIAZUzPvnGHBEDKVQeYVrA+pY4w1RvtjaPJYXc6zQ+GO5AiEAhn1iCifgQt2D4BpVYzZjKY3k63HlUb+3Sa95RO1nqU4q+gIIFhAAGgwwNDE4Nzc3NTMzNTciDH4AzMlqP8LJiE79WirXAh5szMOPz+SXJrkXdYHtqfK8gyDXg0HCwJZhJMmbMfzfoCvX/mV0gUWrhwg5PjLxv/Rn5JJQh5/of0hjh+vO6zP8GzNRXXJR1p/npkhpigEMioiciujsx2LDdPZVzlA+CT3HQXLCDPtcPZjftu4WG/vohiPexqgyMn32kbbgZBIcBaAA5jBD6lpfS0jHSYRWMgFjTFctSO3UtgfBLNKR4uAM22HVieBcEHHlEMMR4AZ5g/vElVeFQAxZf76s2hXPY2a311D87G6DKhdpTOMrenwQCq/DfBfrlSt+HA7r9+YZp568AtMgyBmaKSw3gratGJELUGDisH4o0Pb5pAtOOtyi2YuQKIcZDWAJa/vtGdK0Y8k0UnwuPBIq9oFNFPGNOL1HaPQen4SxVmfJM2R5e7/iCbmwr9AQfEtdeE8BJ6G1TegzV9FiVbZ8ufwV+IHJJ8PW73F03GAwkbiupgY6pwFf6aI3eWI4uWikqx/WZVJxP6AkJCz1fTIjX+/F+S7O/G+/iMu/OrSdugBzGJox8zdLbLsSy25PlsfpVSlhyOrPYFl+DtNoRyRjjOZ87OFIOBB9B3fg0jkClbNjUa+LzUB6HPP7xxEgt7qJmqwq5WeNi49wQzLZrOEEWXvMAYzRCTvxOzBD6L3EyBqJtWsNwllgrbP2NoUgPkhgXHtvd7CThFI5mzrMQA=="
          aws-region: "ap-south-1"

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./apps/dashboard/web/dist s3://my-cdn-test-bucket --delete

      - run: mvn package -Dakto-image-tag=${{ github.event.inputs.Tag }} -Dakto-build-time=$(eval "date +%s")
      - name: DockerHub login
        if: ${{ github.event.inputs.Environment == 'prod' }}
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
      - name: Convert github branch name to be compatible with docker tag name convention
        id: docker_tag
        run: echo "TAG_SUFFIX=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9]/_/g')" >> $GITHUB_OUTPUT
      - name: Build, tag, and push the image to DockerHub
        if: ${{ github.event.inputs.Environment == 'prod' }}
        id: build-image-dockerhub
        env:
          ECR_REGISTRY: aktosecurity
          ECR_REPOSITORY: akto-api-security
          IMAGE_TAG: ${{ github.event.inputs.Tag }}_${{ steps.docker_tag.outputs.TAG_SUFFIX }}
          IMAGE_TAG_DASHBOARD: ${{ github.event.inputs.Deploy == 'true' && '-t aktosecurity/akto-api-security-dashboard:flash' || '' }}
          IMAGE_TAG_TESTING: ${{ github.event.inputs.Deploy == 'true' && '-t aktosecurity/akto-api-testing:flash' || '' }}
        run: |
          docker buildx create --use
          # Build a docker container and push it to DockerHub 
          cd apps/dashboard
          docker buildx build --platform linux/arm64/v8,linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY-dashboard:$IMAGE_TAG $IMAGE_TAG_DASHBOARD . --push
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY-dashboard:$IMAGE_TAG"   
          cd ../testing
          docker buildx build --platform linux/arm64/v8,linux/amd64 -t $ECR_REGISTRY/akto-api-testing:$IMAGE_TAG $IMAGE_TAG_TESTING . --push
          echo "::set-output name=image::$ECR_REGISTRY/akto-api-testing:$IMAGE_TAG"       
      - name: Update flash staging
        if: ${{ github.event.inputs.Environment == 'prod' && github.event.inputs.Deploy == 'true' }}
        run: |
          curl https://flash.staging.akto.io/api/takeUpdate -H X-API-KEY:${{secrets.AKTO_API_KEY}}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run CI/CD tests
        if: ${{ github.event.inputs.Environment == 'prod' && github.event.inputs.Deploy == 'true' }}
        uses: oren-akto/akto-github-action@v1.0.0
        with:
          AKTO_DASHBOARD_URL: ${{vars.AKTO_DASHBOARD_URL}}
          AKTO_API_KEY: ${{vars.AKTO_API_KEY}}
          AKTO_TEST_ID: ${{vars.AKTO_TEST_ID}}
          START_TIME_DELAY: 180
